context:
  name: supabase-auth
  version: "2.28.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/supabase_auth/supabase_auth-${{ version }}.tar.gz
  sha256: 2bb8f18ff39934e44b28f10918db965659f3735cd6fbfcc022fe0b82dbf8233e

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.8.3,<0.9.0
  run:
    - python >=${{ python_min }}
    - httpx >=0.26,<0.29
    - pydantic >=1.10,<3
    - pyjwt >=2.10.1,<3

tests:
  - python:
      imports:
        - supabase_auth
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Python client implementation for Supabase Auth
  homepage: https://github.com/supabase/supabase-py/tree/main/src/auth
  repository: https://github.com/supabase/supabase-py/tree/main/src/auth

extra:
  recipe-maintainers:
    - anand2312
    - J0
    - timkpaine
